### ISSUE TITLE
Add responsive download button

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/CodingBooks#19]
- Add responsive download button for each book
- The background color of these button will be -> #2b2b2b8c

**Comment by ORKO06** [comment]
I would like to work on it

**Comment by mohitjaisal** [comment]
Go ahead @ORKO06 👍🏻

**Comment by vedikamujgule** [comment]
@mohitjaisal the color code given by you is very transparent.. it is not visible on the book image properly

**Comment by vedikamujgule** [comment]
@mohitjaisal PR is up against this issue.. please review the same. Thankyou

**Comment by mohitjaisal** [comment]
@vedikamujgule merged thanks.. 👍🏻
