### ISSUE TITLE
Remove github corner buttons in mobile mode

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/CodingBooks#23]
- Remove github corner button in mobile mode it
- give the repository link in the footer just for mobile mode
![Screenshot_20211010_111741](https://user-images.githubusercontent.com/23385605/136684080-516dd33e-48ea-49c5-8192-4badf76569c6.jpg)

**Comment by Yomna-moustafa** [comment]
Hey! I would like to work on this issue please assign it to me if not already assigned

**Comment by mohitjaisal** [comment]
@Yomna-moustafa you can start working on it 👍🏻

**Comment by vedikamujgule** [comment]
I would like to contribute to this issue.. please assign
