### ISSUE TITLE
Download Button Problem

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/CodingBooks#30]
There is a bit problem with the button for the 6th book. The problem is in the positioning of that button 👇
![image](https://user-images.githubusercontent.com/23385605/137590504-8a87e764-ac07-4ff1-8e5a-c69724ac8e57.png)

**Comment by Sagargajare** [comment]
@mohitjaisal I understood the problem. I would like to fix that. Can you assign it to me?

**Comment by mohitjaisal** [comment]
@Sagargajare Go ahead 👍🏻
