### ISSUE TITLE
Enhancement of site's HTML and CSS syntax and structure to Improve SEO attributes and accessibility requirements

### ISSUE THREAD

**Issue by LittleMissButtons** [mohitjaisal/CodingBooks#53]
****I was looking at your 'README.md' issue although I couldn't quite understand your full requirements. 

However, I did spot several improvements that could be made to the site's HTML and CSS syntax and structure. These would improve SEO attributes, accessibility requirements and structure without any changes to your layout.

Also, I was able to fix #Issue 48 the 'Coding books' logo and text so that is linked to the homepage and can be clicked on. Previously was hidden in the background with no link on the logo.

I would be happy to provide this under a pull request for your approval.

****Please could you label this as an Hacktoberfest issue so that it counts towards my submissions**** 

P.S love the idea of your website as it is really useful having accessible coding literature.

**Comment by mohitjaisal** [comment]
Go ahead @LittleMissButtons

**Comment by LittleMissButtons** [comment]
Pull request opened with the proposed changes

**Comment by LittleMissButtons** [comment]
Pull request closed
